# Generated by Django 5.2.17 on 2026-08-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug-url', unique=True),
            preserve_default=False,
        ),
    ]
